name: gcp-storage-sync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: omppye-tech/gcp-storage-sync@master
        with:
          args: -d
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_CREDENTIALS }}
          GCP_STORAGE_BUCKET: 'sellaci.com'
          SOURCE_DIR: '.'
