name: Deployment Cloud Storage

on:
  push:
    branches:
    - main
  

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIALS}}

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'index.html'
        destination: 'sellaci.com'
